spring:
  application:
    name: ai-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

ollama:
  base-url: http://localhost:11434
  chat-model: mistral:latest
  embedding-model: nomic-embed-text:latest

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

info:
  app:
    name: AI Dev Copilot
    description: AI-powered Backend Engineering Assistant
    version: 1.0.0